import Link from "next/link";
import { BookOpen, Feather, Headphones, Layers, Sparkles, Wand2 } from "lucide-react";

const features = [
  { icon: Layers,    title: "Multi-Chapter Stories",    desc: "3–10 chapters with full narrative continuity tracked across the entire story." },
  { icon: Sparkles,  title: "Claude-Powered Prose",     desc: "Every chapter written by Claude with genre-aware voice and consistent characters." },
  { icon: Wand2,     title: "AI Scene Illustrations",   desc: "Cinematic chapter images generated by fal.ai Flux, styled to your choice." },
  { icon: Headphones,title: "Audio Narration",           desc: "Text-to-speech narration for every chapter — listen while you read." },
  { icon: BookOpen,  title: "Personal Library",         desc: "All your stories saved and accessible forever. Pick up where you left off." },
  { icon: Feather,   title: "Real-Time Streaming",      desc: "Watch your story write itself word by word as Claude generates it live." },
];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-ink-900 flex flex-col">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 py-4 border-b border-ink-800">
        <div className="flex items-center gap-2">
          <Feather size={20} className="text-gold-500" />
          <span className="font-serif text-lg font-semibold text-parchment-100">
            Dream<span className="text-gold-500">Wild</span>
          </span>
        </div>
        <div className="flex items-center gap-3">
          <Link href="/login"  className="text-sm text-parchment-400 hover:text-parchment-100 transition-colors px-3 py-1.5">Sign in</Link>
          <Link href="/signup" className="text-sm bg-gold-500 text-ink-900 hover:bg-gold-400 px-4 py-1.5 rounded-sm font-medium transition-colors">Get started</Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="flex flex-col items-center text-center px-6 py-24 gap-8 relative overflow-hidden">
        <div className="absolute inset-0 bg-gold-glow pointer-events-none" />
        <div className="inline-flex items-center gap-2 text-xs font-sans uppercase tracking-widest text-gold-600 border border-gold-800/50 bg-gold-900/20 px-3 py-1 rounded-full">
          <Sparkles size={11} /> Powered by Claude · fal.ai · OpenAI TTS
        </div>
        <h1 className="font-serif text-4xl md:text-6xl lg:text-7xl font-bold text-parchment-100 max-w-3xl leading-tight">
          Where Your Story<br />
          <span className="text-gold-500 italic">Becomes Legend</span>
        </h1>
        <p className="text-parchment-300 font-body text-lg md:text-xl max-w-xl leading-relaxed">
          Choose your genre, set the stage, and watch Claude write a multi-chapter story—complete with AI illustrations and audio narration—in real time.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 bg-gold-500 text-ink-900 hover:bg-gold-400 px-8 py-3.5 rounded-sm font-sans font-semibold text-base transition-all shadow-[0_0_30px_rgba(201,168,76,0.3)] hover:shadow-[0_0_40px_rgba(201,168,76,0.5)]"
          >
            <Feather size={16} />
            Start forging
          </Link>
          <Link
            href="/login"
            className="inline-flex items-center gap-2 border border-gold-800/60 text-gold-400 hover:bg-gold-800/10 px-8 py-3.5 rounded-sm font-sans text-base transition-colors"
          >
            Sign in
          </Link>
        </div>
      </section>

      {/* Features */}
      <section className="px-6 py-20 max-w-5xl mx-auto w-full">
        <h2 className="font-serif text-2xl text-parchment-100 text-center mb-12">
          Everything Tale Forge wasn&apos;t
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {features.map((f) => (
            <div key={f.title} className="bg-ink-800 border border-ink-700 rounded-sm p-5 flex flex-col gap-3 hover:border-gold-800/60 transition-colors">
              <f.icon size={20} className="text-gold-500" />
              <h3 className="font-serif text-base text-parchment-100">{f.title}</h3>
              <p className="text-sm text-parchment-400 font-sans leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="flex flex-col items-center px-6 py-20 gap-6 border-t border-ink-800">
        <h2 className="font-serif text-3xl text-parchment-100">Ready to write your legend?</h2>
        <Link
          href="/signup"
          className="inline-flex items-center gap-2 bg-gold-500 text-ink-900 hover:bg-gold-400 px-8 py-3.5 rounded-sm font-sans font-semibold text-base transition-all"
        >
          <Feather size={16} />
          Create free account
        </Link>
      </section>

      <footer className="py-6 text-center text-xs text-parchment-400 font-sans border-t border-ink-800">
        DreamWild — built with Claude, fal.ai, Supabase, FastAPI &amp; Next.js
      </footer>
    </main>
  );
}
